# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-03 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='邮箱')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('weibo', models.CharField(blank=True, max_length=255, null=True, verbose_name='新浪微博')),
                ('blog', models.CharField(blank=True, max_length=255, null=True, verbose_name='个人网站')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
                ('profile', models.CharField(blank=True, max_length=255, null=True, verbose_name='个人简介')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('au', models.IntegerField(default=0, verbose_name='用户活跃度')),
                ('last_ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='上次访问IP')),
                ('email_verified', models.BooleanField(default=False, verbose_name='邮箱是否验证')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='用户注册时间')),
                ('topic_num', models.IntegerField(default=0, verbose_name='帖子数')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否是管理员')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailVerified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=None, max_length=255, verbose_name='邮箱验证口令')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FindPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_a', to=settings.AUTH_USER_MODEL, verbose_name='偶像')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_b', to=settings.AUTH_USER_MODEL, verbose_name='粉丝')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set([('user_a', 'user_b')]),
        ),
    ]
